IMAGE_WIDTH : 128
IMAGE_HEIGHT : IMAGE_WIDTH
IMAGE_DEPTH : 3
DATA_DIR_MANIFACTURER : "../models/planes_2022-04-02_14-35-43.h5"
DATA_DIR_FAMILY : "../models/family_2022-04-05_22-55-09.h5"
DATA_DIR_CLASSE_MANUFACTURER : "../models/classes_names.txt"
DATA_DIR_CLASSE_FAMILY : "../models/families.txt"
DATA_DIR_FAMILY_TL : "../models/family_tl.h5"
DATA_DIR_MANUFACTURER_TL : "../app/manufacturer_tl.h5"
DATA_DIR_FAMILY_SVM : "../models/model_svc.sav"
DATA_DIR_MANIFACTURER_SVM : "../models/manufacturer.pickle"